


#include "pch.h"
#include "framework.h"
#include "pngtotm2.h"
#include "pngtotm2Dlg.h"
#include "util.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif



int main(int argc, char** argv)
{
	setlocale(LC_CTYPE, "jpn");
	if (argc == 1)
	{
		return wWinMain(::GetModuleHandle(NULL), NULL, ::GetCommandLine(), SW_HIDE);
	}
	else if (argc == 2)
	{
		char* filename = argv[1];
		int codepage = GetConsoleOutputCP();
		int filenamesize = strlen(filename);
		const int wfilenamesize = MultiByteToWideChar(codepage, 0, &filename[0], filenamesize , NULL, 0);
		wchar_t* wfilename = new wchar_t[filenamesize+1] {0};
		MultiByteToWideChar(codepage, 0, &filename[0], filenamesize, wfilename,wfilenamesize );
		std::wstring wstrfilename(wfilename);
		std::wstring dirpath = wstrfilename.substr(0, wstrfilename.find_last_of('\\'));
		int error = convertimage(wstrfilename,dirpath);
		delete wfilename;
		if (error!=0)
		{
			ErrMSG(L"Failed Convert Image");
		}
		return 0;
	}
	else
	{
		ErrMSG(L"invalid argument");
		return -1;
	}
}


BEGIN_MESSAGE_MAP(Cpngtotm2App, CWinApp)
	ON_COMMAND(ID_HELP, &CWinApp::OnHelp)
END_MESSAGE_MAP()




Cpngtotm2App::Cpngtotm2App()
{

	m_dwRestartManagerSupportFlags = AFX_RESTART_MANAGER_SUPPORT_RESTART;

}



Cpngtotm2App theApp;




BOOL Cpngtotm2App::InitInstance()
{

	INITCOMMONCONTROLSEX InitCtrls;
	InitCtrls.dwSize = sizeof(InitCtrls);

	InitCtrls.dwICC = ICC_WIN95_CLASSES;
	InitCommonControlsEx(&InitCtrls);

	CWinApp::InitInstance();


	AfxEnableControlContainer();

	CShellManager *pShellManager = new CShellManager;

	CMFCVisualManager::SetDefaultManager(RUNTIME_CLASS(CMFCVisualManagerWindows));

	SetRegistryKey(_T("Local application generated by the Application Wizard"));

	Cpngtotm2Dlg dlg;
	m_pMainWnd = &dlg;
	INT_PTR nResponse = dlg.DoModal();
	if (nResponse == IDOK)
	{

	}
	else if (nResponse == IDCANCEL)
	{

	}
	else if (nResponse == -1)
	{
		TRACE(traceAppMsg, 0, "Warning: Failed to create dialog. The application will exit unexpectedly.\n");
		TRACE(traceAppMsg, 0, "Warning: If you are using the MFC control in a dialog, the #define _AFX_NO_MFC_CONTROLS_IN_DIALOGS cannot be specified.\n");
	}


	if (pShellManager != nullptr)
	{
		delete pShellManager;
	}

#if !defined(_AFXDLL) && !defined(_AFX_NO_MFC_CONTROLS_IN_DIALOGS)
	ControlBarCleanUp();
#endif


	return FALSE;
}

